### ISSUE TITLE
gcc unrecognized command when installing on Civo Cloud

### ISSUE THREAD

**Issue by lucj** [falcosecurity/falco#2733]
**Describe the bug**

Cannot install Falco in Civo Cloud on a Kubernetss 1.27.1 cluster

In a new Kubernetes cluster running on Civo I installed Falco Helm chart 3.5.0
Falco cannot be installed, I get the following logs:

```
k logs falco-82fjx -n falco -c falco-driver-loader
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.35.1, driver version=5.0.1+driver, arch=x86_64, kernel release=6.1.28-2-virt, kernel version=3
* Running falco-driver-loader with: driver=module, compile=yes, download=yes

================ Cleaning phase ================

* 1. Check if kernel module 'falco' is still loaded:
- OK! There is no 'falco' module loaded.

* 2. Check all versions of kernel module 'falco' in dkms:
- OK! There are no 'falco' module versions in dkms.

[SUCCESS] Cleaning phase correctly terminated.

================ Cleaning phase ================

* Looking for a falco module locally (kernel 6.1.28-2-virt)
* Filename 'falco_alpine_6.1.28-2-virt_3.ko' is composed of:
 - driver name: falco
 - target identifier: alpine
 - kernel release: 6.1.28-2-virt
 - kernel version: 3
* Trying to download a prebuilt falco module from https://download.falco.org/driver/5.0.1%2Bdriver/x86_64/falco_alpine_6.1.28-2-virt_3.ko
curl: (22) The requested URL returned error: 404 
Unable to find a prebuilt falco module
install: /usr/lib/gcc/x86_64-linux-gnu/5/
* Trying to dkms install falco module with GCC /usr/bin/gcc
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Creating symlink /var/lib/dkms/falco/5.0.1+driver/source ->
                 /usr/src/falco-5.0.1+driver

DKMS: add completed.

Kernel preparation unnecessary for this kernel.  Skipping...

Building module:
cleaning build area...
'/tmp/falco-dkms-make'...(bad exit status: 2)
* Running dkms build failed, dumping /var/lib/dkms/falco/5.0.1+driver/build/make.log (with GCC /usr/bin/gcc)
DKMS make.log for falco-5.0.1+driver for kernel 6.1.28-2-virt (x86_64)
Mon Aug 21 09:36:41 UTC 2023
'/tmp/falco-dkms-make' -C /lib/modules/6.1.28-2-virt/build M=/var/lib/dkms/falco/5.0.1+driver/build modules
make[1]: Entering directory '/host/usr/src/linux-headers-6.1.28-2-virt'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924
  You are using:           gcc (Debian 5.5.0-12) 5.5.0 20171010
  CC [M]  /var/lib/dkms/falco/5.0.1+driver/build/main.o
gcc: error: unrecognized command line option '-ftrivial-auto-var-init=zero'
gcc: error: unrecognized command line option '-fzero-call-used-regs=used-gpr'
gcc: error: unrecognized command line option '-Wimplicit-fallthrough=5'
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/falco/5.0.1+driver/build/main.o] Error 1
make[1]: *** [Makefile:2012: /var/lib/dkms/falco/5.0.1+driver/build] Error 2
make[1]: Leaving directory '/host/usr/src/linux-headers-6.1.28-2-virt'
make: *** [Makefile:16: all] Error 2
install: /usr/lib/gcc/x86_64-linux-gnu/5/
```

- Falco version:
0.35.1
- Cloud provider or hardware configuration:
Kubernetes 1.27.1 on Civo Cloud
- Installation method:
Helm (chart version 3.5.0)

**Comment by Andreagit97** [comment]
thank you for reporting this! Unfortunately, this is a known issue and we are working to fix it https://github.com/falcosecurity/falco/pull/2718
In the meanwhile, you could try the [modern bpf](https://falco.org/docs/event-sources/kernel/#modern-ebpf-probe), it is already shipped within Falco so you don't need to build anything!

**Comment by FedeDP** [comment]
This should now be fixed in latest Falco 0.36.0!

**Comment by Andreagit97** [comment]
[Falco 0.36](https://github.com/falcosecurity/falco/releases/tag/0.36.0) should solve this issue, I will close it. Feel free to reopen if this is not solved :)!

**Comment by lucj** [comment]
I've installed falco helm 3.7.1 (falco 0.36.0) but still getting the same issue:

```
k logs falco-v7hzh -n falco -c falco-driver-loader
* Setting up /usr/src links from host
* Running falco-driver-loader for: falco version=0.36.0, driver version=6.0.1+driver, arch=x86_64, kernel release=6.1.28-2-virt, kernel version=3
* Running falco-driver-loader with: driver=module, compile=yes, download=yes

================ Cleaning phase ================

* 1. Check if kernel module 'falco' is still loaded:
- OK! There is no 'falco' module loaded.

* 2. Check all versions of kernel module 'falco' in dkms:
- OK! There are no 'falco' module versions in dkms.

[SUCCESS] Cleaning phase correctly terminated.

================ Cleaning phase ================

* Looking for a falco module locally (kernel 6.1.28-2-virt)
* Filename 'falco_alpine_6.1.28-2-virt_3.ko' is composed of:
 - driver name: falco
 - target identifier: alpine
 - kernel release: 6.1.28-2-virt
 - kernel version: 3
* Trying to download a prebuilt falco module from https://download.falco.org/driver/6.0.1%2Bdriver/x86_64/falco_alpine_6.1.28-2-virt_3.ko
curl: (22) The requested URL returned error: 404
Unable to find a prebuilt falco module
install: /usr/lib/gcc/x86_64-linux-gnu/12/
* Trying to dkms install falco module with GCC /usr/bin/gcc
Sign command: /lib/modules/6.1.28-2-virt/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
Certificate or key are missing, generating self signed certificate for MOK...
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"
Creating symlink /var/lib/dkms/falco/6.0.1+driver/source -> /usr/src/falco-6.0.1+driver

Building module:
Cleaning build area...
'/tmp/falco-dkms-make'...(bad exit status: 2)
* Running dkms build failed, dumping /var/lib/dkms/falco/6.0.1+driver/build/make.log (with GCC /usr/bin/gcc)
DKMS make.log for falco-6.0.1+driver for kernel 6.1.28-2-virt (x86_64)
Wed Oct  4 15:42:33 UTC 2023
'/tmp/falco-dkms-make' -C /lib/modules/6.1.28-2-virt/build M=/var/lib/dkms/falco/6.0.1+driver/build modules
make[1]: Entering directory '/host/usr/src/linux-headers-6.1.28-2-virt'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924
  You are using:           gcc (Debian 12.2.0-14) 12.2.0
  CC [M]  /var/lib/dkms/falco/6.0.1+driver/build/main.o
cc1: error: cannot load plugin ./scripts/gcc-plugins/stackleak_plugin.so: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
cc1: error: cannot load plugin ./scripts/gcc-plugins/latent_entropy_plugin.so: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/falco/6.0.1+driver/build/main.o] Error 1
make[1]: *** [Makefile:2012: /var/lib/dkms/falco/6.0.1+driver/build] Error 2
make[1]: Leaving directory '/host/usr/src/linux-headers-6.1.28-2-virt'
make: *** [Makefile:16: all] Error 2
install: /usr/lib/gcc/x86_64-linux-gnu/11/
* Trying to dkms install falco module with GCC /usr/bin/gcc-11
Sign command: /lib/modules/6.1.28-2-virt/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Building module:
Cleaning build area...
'/tmp/falco-dkms-make'...(bad exit status: 2)
* Running dkms build failed, dumping /var/lib/dkms/falco/6.0.1+driver/build/make.log (with GCC /usr/bin/gcc-11)
DKMS make.log for falco-6.0.1+driver for kernel 6.1.28-2-virt (x86_64)
Wed Oct  4 15:42:34 UTC 2023
'/tmp/falco-dkms-make' -C /lib/modules/6.1.28-2-virt/build M=/var/lib/dkms/falco/6.0.1+driver/build modules
make[1]: Entering directory '/host/usr/src/linux-headers-6.1.28-2-virt'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924
  You are using:           gcc-11 (Debian 11.3.0-12) 11.3.0
  CC [M]  /var/lib/dkms/falco/6.0.1+driver/build/main.o
gcc-11: error: unrecognized command-line option '-ftrivial-auto-var-init=zero'
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/falco/6.0.1+driver/build/main.o] Error 1
make[1]: *** [Makefile:2012: /var/lib/dkms/falco/6.0.1+driver/build] Error 2
make[1]: Leaving directory '/host/usr/src/linux-headers-6.1.28-2-virt'
make: *** [Makefile:16: all] Error 2
install: /usr/lib/gcc/x86_64-linux-gnu/12/
* Trying to dkms install falco module with GCC /usr/bin/gcc-12
Sign command: /lib/modules/6.1.28-2-virt/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub
DIRECTIVE: MAKE="'/tmp/falco-dkms-make'"

Building module:
Cleaning build area...
'/tmp/falco-dkms-make'...(bad exit status: 2)
* Running dkms build failed, dumping /var/lib/dkms/falco/6.0.1+driver/build/make.log (with GCC /usr/bin/gcc-12)
DKMS make.log for falco-6.0.1+driver for kernel 6.1.28-2-virt (x86_64)
Wed Oct  4 15:42:35 UTC 2023
'/tmp/falco-dkms-make' -C /lib/modules/6.1.28-2-virt/build M=/var/lib/dkms/falco/6.0.1+driver/build modules
make[1]: Entering directory '/host/usr/src/linux-headers-6.1.28-2-virt'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: gcc (Alpine 12.2.1_git20220924-r10) 12.2.1 20220924
  You are using:           gcc-12 (Debian 12.2.0-14) 12.2.0
  CC [M]  /var/lib/dkms/falco/6.0.1+driver/build/main.o
cc1: error: cannot load plugin ./scripts/gcc-plugins/stackleak_plugin.so: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
cc1: error: cannot load plugin ./scripts/gcc-plugins/latent_entropy_plugin.so: libc.musl-x86_64.so.1: cannot open shared object file: No such file or directory
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/falco/6.0.1+driver/build/main.o] Error 1
make[1]: *** [Makefile:2012: /var/lib/dkms/falco/6.0.1+driver/build] Error 2
make[1]: Leaving directory '/host/usr/src/linux-headers-6.1.28-2-virt'
make: *** [Makefile:16: all] Error 2
* Trying to load a system falco module, if present
Consider compiling your own falco driver and loading it or getting in touch with the Falco community
```

**Comment by Andreagit97** [comment]
@lucj have you ever tried the [modern bpf](https://falco.org/docs/event-sources/kernel/#modern-ebpf-probe)? it should solve your issue

**Comment by lucj** [comment]
@Andreagit97 I've not tried it yet but I'll definitely do. Thanks a lot 👍

**Comment by lucj** [comment]
Works like a charm with modern bpf 💯
