### ISSUE TITLE
Support containerd

### ISSUE THREAD

**Issue by voidengineer** [falcosecurity/falco#381]
This is a feature request.

The company I am working for is currently desinging and building an internal/private Kubernetes-based infrastructure. We will no longer even install the docker-engine on the nodes, but run everything with [containerd](https://github.com/containerd/containerd) and its [cri-plugin](https://github.com/containerd/cri).

It would be great if falco could talk to the containerd.sock instead of docker.sock.

**Comment by mstemm** [comment]
Are the two wire-compatible? If so you could link the path, or run falco in a container such that containerd.sock maps to `/host/var/run/docker.sock` inside the container.

**Comment by voidengineer** [comment]
I don't think so.
containerd is a daemon for managing the container-lifecycle on its own. It will be used in future versions of Docker.
Kubernetes can use different container-runtimes as long as they implement Kubernetes CRI (Container Runtime Interface). They ship their own implementation of CRI for Docker ([dockershim](https://github.com/kubernetes/kubernetes/tree/master/pkg/kubelet/dockershim)).
containerd implements CRI via plugin ([cri-containerd](https://github.com/containerd/cri)) and there is even another runtime called [CRI-O](https://github.com/kubernetes-incubator/cri-o).

**Comment by mstemm** [comment]
Ah, so the change would be to additionally communicate with containerd for those container types, in cases where we need conainer-level information.

**Comment by voidengineer** [comment]
Exactly. It should be configurable wether falco gets container-level information from docker or from containerd (or maybe even CRI as an abstraction layer?).

**Comment by bhperry** [comment]
Using the CRI abstraction would be great..... I've been trying to use falco on kubernetes with CRI-O, and only just recently realized that it was incompatible (the `Runtime error: Invalid container ID (expected 'docker://{ID}' or 'rkt://{ID}'): cri-o://<CONTAINER-ID>. Exiting.` error was hidden behind another silently failing error that prevented falco from even getting to this point)

**Comment by voidengineer** [comment]
Any news on this?

**Comment by mstemm** [comment]
No, no updates yet. We want to do it, but haven't gotten a chance to work on it yet.

**Comment by gdemarcsek** [comment]
+1 this would be cool to have

**Comment by mfdii** [comment]
Fixed in https://github.com/draios/sysdig/pull/1277. The dev build of Falco should have this enabled.

**Comment by axot** [comment]
I checked the lastest Falco 0.14.0, and this issue remain exists. Which version is planning to support?

**Comment by mvisonneau** [comment]
Indeed, unless there is a flag to set in order to use the CRI ? 🤔 

```
Tue Mar 19 09:30:39 2019: Runtime error: Invalid container ID (expected 'docker://{ID}' or 'rkt://{ID}'): containerd://b30dc1181351f24b94f40b46d83efa2392288277215b0b233ae53bb806d619e1. Exiting.
```

**Comment by mfdii** [comment]
0.14.1 (when released) should support this.

**Comment by axot** [comment]
Hello, I build an image from dev branch today, the error does not disappear, advice?

```
root@test-695ff8cbf4-qp7tv:/# echo $FALCO_REPOSITORY
dev
root@test-695ff8cbf4-qp7tv:/# falco --version | cut -d' ' -f3
0.1.2736dev
```

> Fri Apr 12 05:35:04 2019: Runtime error: Invalid container ID (expected 'docker://{ID}' or 'rkt://{ID}'): containerd://2d16d0bf23fcb0db298084b04b310bce70a279a2a96d3dcc2df507164315993c. Exiting.

**Comment by mstemm** [comment]
@axot, It looks like the problem you had was when also using the k8s integration. It isn't yet aware of new container types. I think the change needs to be made [here](https://github.com/draios/sysdig/blob/dev/userspace/libsinsp/k8s_state.cpp#L73). I filed a new issue https://github.com/draios/sysdig/issues/1371 to track that fix.

In the meantime, you should be able to run without -k.

We also have daily dev builds again: https://hub.docker.com/r/falcosecurity/falco/tags.

**Comment by mfdii** [comment]
The image `falcosecurity/falco:dev` should have the fix for containerd support. With the `--cri` option you can specify the path to the `containerd.sock`. The default is `/run/containerd/containerd.sock` or `/host/run/containerd/containerd.sock` when running as a container. We've only tested this on IBM Cloud IKS so any feedback would be appreciated.

**Comment by irony1692** [comment]
@mfdii ,
I have tried to use `falcosecurity/falco:dev` with this yaml on IBM Cloud IKS (1.13.5),
```
apiVersion: v1
kind: Pod
metadata:
  name: falco-test
spec:
  containers:
  - name: falco-test
    image: falcosecurity/falco:dev
    imagePullPolicy: Always
    command: [ "/usr/bin/falco", "--cri", "/run/containerd/containerd.sock"]
  securityContext:
    runAsUser: 0
```

but it is showing this error.
```/usr/bin/falco: unrecognized option '--cri'```

Do you have any advice? Thank you.

**Comment by mfdii** [comment]
Sorry, it’s my fault. We had just done a dev build  before I posted that but it hadn’t picked up the correct package. We are having some problems with signing packages now and as soon as that’s fixed I’ll give you a heads up. Sorry for the confusion.

**Comment by mfdii** [comment]
Alright. I've confirmed the dev build is working again and that it has the containerd support. 

```
09:18 $ kubectl get nodes
NAME            STATUS   ROLES    AGE     VERSION
X.XX.XX.XX   Ready    <none>   7d22h   v1.12.7+IKS

09:18 $ kubectl logs falco-467pf |tail -2
12:46:44.708661342: Notice A shell was spawned in a container with an attached terminal (user=root k8s.ns=default k8s.pod=falco-467pf container=fabeb2e1c6b5 shell=bash parent=<NA> cmdline=bash terminal=34816 container.name=falco container.image=docker.io/falcosecurity/falco:dev)
12:46:52.509993693: Error File below a known binary directory opened for writing (user=root command=touch /bin/hello file=/bin/hello parent=bash pcmdline=bash gparent=<NA>) k8s.ns=default k8s.pod=falco-467pf container=fabeb2e1c6b5
```

However, there's a bug where the `--cri` flag didn't get added as a valid option. I've fixed that in #591 and it should be available in tomorrow's dev build. In the meantime, the default location for the CRI socket is `/run/containerd/containerd.sock` if running directly on the host and `/host/run/containerd/containerd.sock` if running inside a container. You just need to add a volume and a mount to the falco daemonset as below. 

```
          volumeMounts:
            - mountPath: /host/var/run/docker.sock
              name: docker-socket
            - mountPath: /host/run/containerd/containerd.sock
              name: containerd-socket
            - mountPath: /host/dev
              name: dev-fs
...
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
        - name: containerd-socket
          hostPath:
            path: /run/containerd/containerd.sock
        - name: dev-fs
          hostPath:
            path: /dev
```

I'll also get the helm chart and daemonset example updated with this mount. Let me know how your testing goes.

**Comment by irony1692** [comment]
I have configured daemonset yaml as you mentioned, and succeeded to make current `falcosecurity/falco:dev` Running on IBM Cloud IKS!
Thank you so much!

**Comment by voidengineer** [comment]
This feature is part of Falco 0.15
